### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by giggio** [mvlandys/jquery.dragscrollable#1]
Please add a package.json and add jquery.dragscrollable to the npmjs.com repository so we can use it with npm.

**Comment by mvlandys** [comment]
Package.json added

**Comment by giggio** [comment]
Great! I can't find the package on npm. Did you publish it?

**Comment by mvlandys** [comment]
https://www.npmjs.com/package/jquery.dragscrollable

**Comment by giggio** [comment]
Yey! Thanks!!!!
